//======================= Screen Names ===================//
const SCREENS = {
    MAIN: 'main',
    TABS: 'tabs',
    API: 'api',
    SPLASH: 'splash',
    LOGIN: 'login',
    REGISTER: 'register',
    DASHBOARD: 'dashboard',
    DASHBOARDGUEST: 'dashboardGuest',
    LOGIN1: 'login1',
    OTP: 'otp',
    MYPROFILE: 'myprofile',
    EDITPROFILE: 'editprofile',
    SUPPORT: 'Support',
    PROFILE: 'Profile',
    NEWINVESTMENT: 'NewInvestment',
    INDIVISUAL: 'Indivisual',
    BUSINESS: 'Business',
    INDIVISUALDETAILS: 'IndivisualDetails',
    ENTERPRISEVALIDATE: 'EnterpriseValidate',
    ENTERPRISEDETAILS: 'EnterpriseDetails',
    CONTACT: 'contact',
    PAYCASH: 'PayCash',
    COMMITTEE: 'Committee',
    TOTALINVESTMENT: 'TotalInvestment',
    LOANOFFER:'loanoffer',
    APPLYLOAN:'applyloan',
    MYLOAN:'myloan',
    ABOUT:'about',
    PRIVACY:'privacy',
    TERMS:'terms and conditions',
    AMOUNT_ENTER:'amountenter',
    EDITBANK:'editbank',
    MYPLANS:'myplans',
    RAAVILAPLANS:'raavilaplans',
    INVESTMENTOFFERS: 'InvestmentOffers',
    NOTIFICATIONS: 'Notifications',
    PAYMENT:'Payment',
    GUESTDASHBOARD: 'GuestDashboard',
    PAYMENTOTP:'PaymentOtp',
    CASHSTATUSMENU: 'CashStatusMenu',
    BANKACCOUNTDETAILS: 'BankAccountDetails',
    COMMITTEEDETAILS: 'CommitteeDetails',
    SUPPORTCHAT: 'SupportChat',
    MYINVESTMENTS:'MyInvestments',
    ONLINEPAYMENT:'OnlinePayment',
    PAYMENTCONFIRMATION:'PaymentConfirmation',
    WITHDRAWAL:'withdrawal'
};

//==================== Validation Messages =================//
const VALIDATE_FORM = {
    EMAIL: 'Please enter email address.',
    EMAIL_VALID: 'Please enter valid email address.',
    DOB: 'Please enter DOB.',
    LOGOUT: 'Are you sure you want to logout?',
    PRIVACY: 'Please select post privacy.',
    ADDRESS: 'Please enter your address',
    TERMS_AND_CODITION: 'Please Accept Terms & Conditions and Privacy Policy.',
    NAME: 'Please enter name',
    VALID_NAME: 'Please enter valid name',
    MOBILE: 'Please enter mobile no.',
    MOBILE_VALID: 'Please enter valid mobile no.',
    EMAILMOBILE: 'Please enter email/mobile no.',
    VALIDEMAILMOBILE: 'Please enter valid Email/Mobile no.',
    PAN_NUM:'Please enter your pan card no.',
    CREDIT_SCORE:'Please enter your credit score',
    FATHER: "Please enter your father's name",
    MOTHER: "Please enter your mother's name",
    MARITAL: "Please tell your marital status",
    PHYSICAL: "Please tell your physical status",
    OCCUPATION: "Please tell your occupation",
    AADHAR: "Please upload your aadhar",
    PAN: "Please upload your pan",
    ACCOUNT: "Please enter account holder name",
    ACC_NUMBER: "Please enter account number",
    IFSC: "Please enter IFSC code",
    CHEQUE: "Please upload a cancel cheque",
    QUERRY: "Please enter your querry",
    AMOUNT: "Please enter amount",
    ROI: 'Please enter roi',
    FROMTENURE: 'Please select from date',
    TOTENURE: 'Please select to date',
    PINCODE: 'Please enter pincode',
    DATE: 'Please select date',
    ENTERPRISE: 'Please enter enterprise',
    GSTNUMBER: 'Please enter gst number',
    CERTIFICATES: 'Please Upload Certificates',
    RADIOBUTTON: 'Please Select One Option',
    TITLE: 'Please enter your title',
    TYPE: 'Please select Type',
};

export {
    SCREENS,
    VALIDATE_FORM,
};